In [306]:
import pandas as pd

Read the data and find the different vectors

In [307]:
# data_path = ".\original_dataset\dataset_bd_wnames.csv" #Windows
data_path = "original_dataset/dataset_bd_wnames.csv"  #MACos
df = pd.read_csv(data_path)
df.head()
df.iloc[1,:]

ID           HD 203977
sp_type             A0
RAdeg        321.20044
DEdeg        25.880459
PS1gmag            NaN
e_PS1gmag          NaN
PS1rmag         7.6116
e_PS1rmag        0.001
PS1imag            NaN
e_PS1imag          NaN
PS1zmag         7.5167
e_PS1zmag        0.001
PS1ymag        13.5874
e_PS1ymag       0.0028
W1mag             6.88
W2mag            6.919
W3mag            6.946
W4mag            6.484
e_W1mag          0.059
e_W2mag           0.02
e_W3mag          0.016
e_W4mag          0.059
Jmag             6.896
Hmag             6.921
Kmag             6.932
e_Jmag           0.026
e_Hmag           0.024
e_Kmag           0.016
label                0
Name: 1, dtype: object

In [308]:
df.columns, df.shape, len(df[df["label"]==1])


(Index(['ID', 'sp_type', 'RAdeg', 'DEdeg', 'PS1gmag', 'e_PS1gmag', 'PS1rmag',
        'e_PS1rmag', 'PS1imag', 'e_PS1imag', 'PS1zmag', 'e_PS1zmag', 'PS1ymag',
        'e_PS1ymag', 'W1mag', 'W2mag', 'W3mag', 'W4mag', 'e_W1mag', 'e_W2mag',
        'e_W3mag', 'e_W4mag', 'Jmag', 'Hmag', 'Kmag', 'e_Jmag', 'e_Hmag',
        'e_Kmag', 'label'],
       dtype='object'),
 (5669, 29),
 1598)

In [309]:
df.head()

ID   sp_type      RAdeg      DEdeg  PS1gmag  e_PS1gmag  PS1rmag  \
0  *  11 Peg       A0V  326.80817   2.686124    5.556        NaN   5.7600   
1  HD 203977        A0  321.20044  25.880459      NaN        NaN   7.6116   
2  HD  83162  A0III/IV  144.03845 -12.459262   10.512        NaN  10.6920   
3  *  10 Boo      A0Vs  209.66217  21.696203      NaN        NaN      NaN   
4  HD  27616       A0V   65.16255 -20.639620      NaN        NaN      NaN   

   e_PS1rmag  PS1imag  e_PS1imag  ...  e_W2mag  e_W3mag  e_W4mag    Jmag  \
0        NaN   5.9470        NaN  ...    0.050    0.015    0.044   5.562   
1      0.001      NaN        NaN  ...    0.020    0.016    0.059   6.896   
2        NaN  10.8660        NaN  ...    0.020    0.074      NaN  10.408   
3        NaN   6.8603     0.1042  ...    0.046    0.015    0.037   5.671   
4        NaN   6.3206     0.0000  ...    0.072    0.015    0.036   5.430   

     Hmag    Kmag  e_Jmag  e_Hmag  e_Kmag  label  
0   5.539   5.479   0.017   0.026   0.020      0  
1   6.921   6.932   0.026   0.024   0.016      0  
2  10.400  10.378   0.026   0.021   0.023      0  
3   5.717   5.704   0.023   0.063   0.020      0  
4   5.402   5.333   0.054   0.036   0.017      0  

[5 rows x 29 columns]

Fill missing values with the mean of the vector

In [310]:
for column in df.columns:
    if column in ["ID", "sp_type"]: #Skipping these
        continue
  
    df[column] = df[column].fillna(df[column].mean()) #Imputing NA values with mean

df.head()
df.columns, df.shape

(Index(['ID', 'sp_type', 'RAdeg', 'DEdeg', 'PS1gmag', 'e_PS1gmag', 'PS1rmag',
        'e_PS1rmag', 'PS1imag', 'e_PS1imag', 'PS1zmag', 'e_PS1zmag', 'PS1ymag',
        'e_PS1ymag', 'W1mag', 'W2mag', 'W3mag', 'W4mag', 'e_W1mag', 'e_W2mag',
        'e_W3mag', 'e_W4mag', 'Jmag', 'Hmag', 'Kmag', 'e_Jmag', 'e_Hmag',
        'e_Kmag', 'label'],
       dtype='object'),
 (5669, 29))

Encode the vector "sp_type" as it is categorical

In [311]:
X = df.drop('ID', axis=1)


unique_values =len(X["sp_type"].unique()) # 504

X.shape, unique_values

X['sp_type'], _ = pd.factorize(X['sp_type'])
X.head



<bound method NDFrame.head of       sp_type       RAdeg      DEdeg   PS1gmag  e_PS1gmag    PS1rmag  \
0           0  326.808170   2.686124   5.55600    0.02303   5.760000   
1           1  321.200440  25.880459  15.12594    0.02303   7.611600   
2           2  144.038450 -12.459262  10.51200    0.02303  10.692000   
3           3  209.662170  21.696203  15.12594    0.02303  14.982256   
4           0   65.162550 -20.639620  15.12594    0.02303  14.982256   
...       ...         ...        ...       ...        ...        ...   
5664      502   13.245956  49.443574   9.12270    0.23470   9.182300   
5665      502   29.647854  48.432832  15.12594    0.02303   9.553800   
5666      502  346.990957  54.326940  15.12594    0.02303   9.840500   
5667      503  331.173131  46.427253  10.49150    0.06300  10.253800   
5668      503  321.694044  43.812346  15.12594    0.02303   7.847700   

      e_PS1rmag    PS1imag  e_PS1imag   PS1zmag  ...  e_W2mag  e_W3mag  \
0      0.027126   5.947000   0.

Split the dataframe/array into data and ground truth

In [312]:
print(X.shape)
y = X["label"]
X = X.drop(columns=["label"])


X.shape, y.shape


(5669, 28)


((5669, 27), (5669,))

In [313]:
from sklearn.model_selection import train_test_split

X_train,  X_test, y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train.shape, y_train.shape, X_test.shape, y_test.shape

((4535, 27), (4535,), (1134, 27), (1134,))

PCA to find the five vectors with the most variance, five is choosen arbitrarly

In [314]:
from sklearn.decomposition import PCA

pca = PCA(n_components=5)

pca.fit(X_train)
X_train = pca.transform(X_train)
X_test = pca.transform(X_test)

X_train, X_test


(array([[ 1.51264640e+02,  1.82493718e+01,  7.28737180e+00,
          8.30797028e+00, -6.61689866e-03],
        [ 1.39461917e+02,  1.12901286e+02,  1.04089343e+01,
         -5.28225451e+00, -2.38794792e+00],
        [ 1.81468796e+02, -5.90718656e+01, -3.14832852e+01,
         -1.04027885e+01, -9.59790499e-01],
        ...,
        [-1.39997413e+02, -1.50195145e+02,  6.69641822e+00,
          7.22258379e+00, -1.79487759e+00],
        [ 3.72962926e+01, -2.06833593e+02, -9.25752173e+00,
          9.88382057e+00, -1.52042602e+00],
        [-2.48384563e+01,  8.94239391e+01, -1.03258346e+01,
          2.13656546e+00, -1.18854750e+00]]),
 array([[-119.34465049,   13.35944633,  -17.64422317,   -4.65645822,
            2.12184501],
        [ 140.33428152, -213.55759905,   -2.34994964,    4.65875345,
           -1.66764144],
        [-158.95872546,   22.47732497,  -13.7876654 ,   -3.76555343,
            0.3499343 ],
        ...,
        [ 176.47823442,  -25.79159391,  -32.05989098,   -6.9021154

Normalize the dataset wit respect to the traning data X_train

In [315]:
""" from sklearn.preprocessing import Normalizer

normalizer = Normalizer()

X_train = normalizer.fit_transform(X_train)
X_test = normalizer.transform(X_test) """

X_train.shape,X_test.shape,y_train.shape, y_test.shape




((4535, 5), (1134, 5), (4535,), (1134,))

Scale the data with respect to the training data X_train

In [316]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


X_train.shape,X_test.shape,y_train.shape, y_test.shape


((4535, 5), (1134, 5), (4535,), (1134,))

In [317]:
import numpy as np
y_train, y_test = np.array(y_train), np.array(y_test)

In [318]:
X_train.shape,X_test.shape,y_train.shape, y_test.shape

((4535, 5), (1134, 5), (4535,), (1134,))

Neural Net for binary classification 5x64x32x1

In [319]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import TensorDataset, DataLoader



# Convert numpy arrays or pandas DataFrames to PyTorch tensors if needed
X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.long)

# Defining a simple neural network class for binary classification
class NeuralNet(nn.Module):
    def __init__(self, input_size):
        super(NeuralNet, self).__init__()
        self.fc1 = nn.Linear(input_size, 128)
        self.relu = nn.ReLU()        # ReLU activation function
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 1)  # Output layer with single neuron (binary classification)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        x = torch.sigmoid(self.fc3(x))  # Apply sigmoid activation for binary classification of final output
        return x

# Initialize the neural network
input_size = X_train.shape[1]
model = NeuralNet(input_size)

# Define loss function and optimizer
criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Prepare data for training using DataLoader
batch_size = 64
train_dataset = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

# Training loop
num_epochs = 10
for epoch in range(num_epochs):
    running_loss = 0.0
    for inputs, labels in train_loader:
        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(inputs)
        outputs = outputs.squeeze(dim=1)  # Remove extra dimension for binary classification
        loss = criterion(outputs, labels.float())  # Calculate loss

        # Backward pass and optimize
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    # Print average loss per epoch
    print(f"Epoch {epoch+1}, Loss: {running_loss / len(train_loader)}")

# Example: Make predictions
# Assuming X_test is your test data
X_test = torch.tensor(X_test, dtype=torch.float32)
model.eval()  # Switch to evaluation mode
with torch.no_grad():
    predictions = model(X_test)
    predictions = (predictions > 0.5).int()  # Convert probabilities to binary predictions (0 or 1)



Epoch 1, Loss: 0.28440276197564435
Epoch 2, Loss: 0.09712533348462951
Epoch 3, Loss: 0.057771437919475664
Epoch 4, Loss: 0.036573446250822345
Epoch 5, Loss: 0.0251651680700376
Epoch 6, Loss: 0.019137478846741815
Epoch 7, Loss: 0.015854209484401305
Epoch 8, Loss: 0.014588884955180258
Epoch 9, Loss: 0.013910296571467229
Epoch 10, Loss: 0.011243232268869589


In [320]:
# Example: Save trained model
# torch.save(model.state_dict(), './models/binary_classification_model.pth') #Windows
torch.save(model.state_dict(), 'models/binary_classification_model.pth') #MACos

Testing with F1 score as brown dwarfs are rare which is also true in the data set

In [321]:
from sklearn.metrics import f1_score

# Load the trained model
input_size = 5  # Assuming the input size based on X_train
model = NeuralNet(input_size)
# model.load_state_dict(torch.load('./models/binary_classification_model.pth'))  # Load the trained model state  (Windows)
model.load_state_dict(torch.load('models/binary_classification_model.pth'))  # Load the trained model state (MACos)


# Assuming X_test and y_test are your test data
# Convert X_test and y_test to torch tensors if needed
X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

# Prepare test dataset and dataloader
batch_size = 64
test_dataset = TensorDataset(X_test, y_test)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)  # No need to shuffle for testing

# Evaluate the model on the test set using F1 score
model.eval()  # Switch to evaluation mode
y_true = []
y_pred = []
print(test_loader)
with torch.no_grad():
    for inputs, labels in test_loader:
        outputs = model(inputs)
        predicted = (outputs > 0.5).float()  # Convert probabilities to binary predictions (0 or 1)
        y_true.extend(labels.cpu().numpy())
        y_pred.extend(predicted.cpu().numpy())

# Calculate F1 score

f1 = f1_score(y_true, y_pred)
print(f"F1 Score: {f1}")

F1 Score: 1.0


/var/folders/5s/6b113_5n5jj0pcmjdn3s12ym0000gn/T/ipykernel_77498/983934941.py:12: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  X_test = torch.tensor(X_test, dtype=torch.float32)


In [322]:
len(y_true), len(y_pred)

(1134, 1134)

In [323]:
from torch.utils.tensorboard import SummaryWriter  # Import SummaryWriter for TensorBoard
writer = SummaryWriter('logs')  # Logs will be saved in the 'logs' directory

from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix

# Convert tensors to numpy arrays
y_true = np.array(y_true)
y_pred = np.array(y_pred)
y_true.shape, y_pred.shape, y_test.shape



((1134,), (1134, 1), torch.Size([1134]))

In [324]:
# Compute accuracy
accuracy = accuracy_score(y_true, y_pred)

# Compute precision and recall
precision = precision_score(y_true, y_pred, average='binary')  # Change average as needed
recall = recall_score(y_true, y_pred, average='binary')  # Change average as needed

accuracy, precision, recall


(1.0, 1.0, 1.0)

In [325]:
# Compute confusion matrix
conf_matrix = confusion_matrix(y_true, y_pred)

conf_matrix

array([[819,   0],
       [  0, 315]])

In [326]:
# Log evaluation metrics and confusion matrix to TensorBoard
writer.add_scalar('Metrics/Accuracy', accuracy, global_step=0)
writer.add_scalar('Metrics/Precision', precision, global_step=0)
writer.add_scalar('Metrics/Recall', recall, global_step=0)
writer.add_text('Confusion_Matrix', str(conf_matrix), global_step=0)


In [327]:

# Close the writer
writer.close()

